$file = 'C:\Users\Jenn1817\Downloads\digit_crru_frontend\index.html'
$text = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)

$b64Replacement = "ICAgIHdpbmRvdy5zdWJtaXRTZXR0aW5ncyA9IGZ1bmN0aW9uKGUpIHsgCiAgICAgICAgaWYoZSkgZS5wcmV2ZW50RGVmYXVsdCgpOyBsZXQgYnRuID0gbnVsbCwgdHh0ID0gJyc7IGlmKGUgJiYgZS50YXJnZXQpIHsgYnRuID0gZS50YXJnZXQucXVlcnlTZWxlY3RvcignYnV0dG9uW3R5cGU9InN1Ym1pdCJdJyk7IGlmKGJ0bikgeyB0eHQgPSBidG4uaW5uZXJIVE1MOyBidG4uaW5uZXJIVE1MID0gJzxpIGNsYXNzPSJwaC1ib2xkIHBoLXNwaW5uZXIgYW5pbWF0ZS1zcGluIj48L2k+IOKiaOC4seC4meC4l+C4tuC4gS4uLic7IGJ0bi5kaXNhYmxlZCA9IHRydWU7IH0gfQogICAgICAgIGxvY2FsU3RvcmFnZS5zZXRJdGVtKCdDUlJVX0FkbWluVXNlcnMnLCBKU09OLnN0cmluZ2lmeShhZG1pblVzZXJzKSk7CiAgICAgICAgc2Vzc2lvblN0b3JhZ2UucmVtb3ZlSXRlbSgnaG9tZVBvcHVwU2hvd24nKTsgCiAgICAgICAgd2luZG93LmFwaUNhbGwoJ1BPU1QnLCB7IGFjdGlvbjogJ3NhdmVTZXR0aW5ncycsIGlzU2hpcnRTaG9wT3BlbjogaXNTaGlydFNob3BPcGVuLCBhZG1pblVzZXJzOiBhZG1pblVzZXJzIH0pLnRoZW4oKCkgPT4geyBpZihlKSB3aW5kb3cuc2hvd1RvYXN0KCLguJrguLHguJnguJfguLbguIHguKrguLPguYDguKPguYfguIciLCAnc3VjY2VzcycpOyBpZihidG4pIHsgYnRuLmlubmVySFRNTCA9IHR4dDsgYnRuLmRpc2FibGVkID0gZmFsc2U7IH0gfSkuY2F0Y2goKCkgPT4geyBpZihlKSB3aW5kb3cuc2hvd1RvYXN0KCLguJrguLHguJnguJfguLbguIHguKrguLPguYDguKPguYfguIcgKE9mZmxpbmUpIiwgJ3dhcm5pbmcnKTsgaWYoYnRuKSB7IGJ0bi5pbm5lckhUTUwgPSB0eHQ7IGJ0bi5kaXNhYmxlZCA9IGZhbHNlOyB9IH0pOyAKICAgIH07"

$replacement = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($b64Replacement))
$pattern = "(?s)    window\.submitSettings = function\(e\) \{.*?    \};"
$text = [regex]::Replace($text, $pattern, $replacement, [System.Text.RegularExpressions.RegexOptions]::Multiline)

[System.IO.File]::WriteAllText($file, $text, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Fixed submitSettings syntax error!"
