$content = Get-Content -Path "C:\Users\Jenn1817\.gemini\antigravity\scratch\digit_crru\index.html" -Raw -Encoding UTF8

$content = $content.Replace(
    "                        // SYNC: ดึงสถานะใบประกาศนียบัตรที่ฝังมาในสถานะ (ส่วนที่ 4 ของ pipe |)`n                        if (stParts.length > 3) {`n                            i.certEnabled = stParts[3] === 'true';`n                        } else if (i.certEnabled !== undefined && i.certEnabled !== null && i.certEnabled !== `"`") {`n                            i.certEnabled = (i.certEnabled === true || String(i.certEnabled).toLowerCase() === 'true');`n                        } else {`n                            i.certEnabled = certEventStatus[i.id] === true;`n                        }`n                        `n                        // อัปเดต Object หลักเพื่อใช้แสดงผลในส่วนอื่นๆ โดยไม่ต้องกลัวโดนทับ",
    "                        // SYNC: ดึงสถานะใบประกาศนียบัตรที่ฝังมาในสถานะ (ส่วนที่ 4 ของ pipe |)`n                        if (stParts.length > 3) {`n                            i.certEnabled = stParts[3] === 'true';`n                        } else if (i.certEnabled !== undefined && i.certEnabled !== null && i.certEnabled !== `"`") {`n                            i.certEnabled = (i.certEnabled === true || String(i.certEnabled).toLowerCase() === 'true');`n                        } else {`n                            i.certEnabled = certEventStatus[i.id] === true;`n                        }`n                        `n                        i.lat = stParts.length > 4 ? stParts[4] : '';`n                        i.lng = stParts.length > 5 ? stParts[5] : '';`n                        `n                        // อัปเดต Object หลักเพื่อใช้แสดงผลในส่วนอื่นๆ โดยไม่ต้องกลัวโดนทับ"
)

$content = $content.Replace(
    "            return ``${d.getDate()} ${m[d.getMonth()]} ${d.getFullYear() + 543}${withTime ? `` `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`` : ''}``;`n        };",
    "            return ``${d.getDate()} ${m[d.getMonth()]} ${d.getFullYear() + 543}${withTime ? `` `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`` : ''}``;`n        };`n        `n        window.getCurrentAdminLocation = function(latId, lngId) {`n            if (navigator.geolocation) {`n                const btn = event.currentTarget;`n                const txt = btn.innerHTML;`n                btn.innerHTML = '<i class=`"ph-bold ph-spinner animate-spin`"></i> รอสักครู่...';`n                btn.disabled = true;`n                navigator.geolocation.getCurrentPosition(function(position) {`n                    document.getElementById(latId).value = position.coords.latitude;`n                    document.getElementById(lngId).value = position.coords.longitude;`n                    window.showToast('ดึงพิกัด GPS สำเร็จ', 'success');`n                    btn.innerHTML = txt; btn.disabled = false;`n                }, function(error) {`n                    window.showToast('ไม่สามารถดึงพิกัดได้ (โปรดอนุญาต GPS)', 'error');`n                    btn.innerHTML = txt; btn.disabled = false;`n                }, { enableHighAccuracy: true });`n            } else {`n                window.showToast('เบราว์เซอร์ไม่รองรับ GPS', 'error');`n            }`n        };`n`n        window.getDistanceFromLatLonInMeters = function(lat1, lon1, lat2, lon2) {`n            const R = 6371e3;`n            const phi1 = lat1 * Math.PI/180;`n            const phi2 = lat2 * Math.PI/180;`n            const deltaPhi = (lat2-lat1) * Math.PI/180;`n            const deltaLambda = (lon2-lon1) * Math.PI/180;`n            const a = Math.sin(deltaPhi/2) * Math.sin(deltaPhi/2) +`n                      Math.cos(phi1) * Math.cos(phi2) *`n                      Math.sin(deltaLambda/2) * Math.sin(deltaLambda/2);`n            const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));`n            return R * c;`n        };"
)

$content = $content.Replace(
    "            document.getElementById('edit-event-date').value = parsedDate; `n            document.getElementById('edit-event-location').value = e.location; `n            document.getElementById('editEventModal').classList.remove('hidden');",
    "            document.getElementById('edit-event-date').value = parsedDate; `n            document.getElementById('edit-event-location').value = e.location; `n            document.getElementById('edit-event-lat').value = e.lat || ''; `n            document.getElementById('edit-event-lng').value = e.lng || ''; `n            document.getElementById('editEventModal').classList.remove('hidden');"
)

$content = $content.Replace(
    "            if (evO) {`n                const now = new Date();",
    "            if (evO) {`n                if (evO.lat && evO.lng) {`n                    if (!navigator.geolocation) {`n                        window.showToast('เบราว์เซอร์ไม่รองรับ GPS ไม่สามารถเช็คชื่อได้', 'error');`n                        return;`n                    }`n                    try {`n                        const position = await new Promise((resolve, reject) => {`n                            navigator.geolocation.getCurrentPosition(resolve, reject, { enableHighAccuracy: true, timeout: 10000 });`n                        });`n                        const dist = window.getDistanceFromLatLonInMeters(`n                            parseFloat(evO.lat), parseFloat(evO.lng),`n                            position.coords.latitude, position.coords.longitude`n                        );`n                        if (dist > 150) { `n                            if (err) { err.innerHTML = 'คุณไม่ได้อยู่ในพื้นที่จัดกิจกรรม (ห่าง ' + Math.round(dist) + ' เมตร)'; err.classList.remove('hidden'); }`n                            window.showToast('นอกพื้นที่กิจกรรม!', 'error');`n                            return;`n                        }`n                    } catch(geoErr) {`n                        if (err) { err.innerHTML = 'ไม่สามารถดึงพิกัดได้ โปรดเปิดใช้งานและอนุญาต GPS บนอุปกรณ์'; err.classList.remove('hidden'); }`n                        window.showToast('ข้อผิดพลาด GPS', 'error');`n                        return;`n                    }`n                }`n                const now = new Date();"
)

$content = $content.Replace(
    "                                <div><label class=`"block text-xs font-bold mb-2 text-slate-600`">สถานที่ *</label><input type=`"text`" id=`"new-event-location`" required class=`"w-full px-5 py-3.5 rounded-2xl border border-slate-200 bg-white/80 focus:border-primary outline-none transition-all`"></div>`n                                <div class=`"mt-2 md:mt-0`"><button type=`"submit`" class=`"w-full px-6 py-3.5 bg-admin text-white font-bold rounded-2xl hover:bg-admin_hover transition-colors shadow-lg`">สร้าง</button></div>",
    "                                <div><label class=`"block text-xs font-bold mb-2 text-slate-600`">สถานที่ *</label><input type=`"text`" id=`"new-event-location`" required class=`"w-full px-5 py-3.5 rounded-2xl border border-slate-200 bg-white/80 focus:border-primary outline-none transition-all`"></div>`n                                <div class=`"mt-2 md:mt-0`"><button type=`"submit`" class=`"w-full px-6 py-3.5 bg-admin text-white font-bold rounded-2xl hover:bg-admin_hover transition-colors shadow-lg`">สร้าง</button></div>`n                            </div>`n                            <div class=`"bg-white/50 border border-white shadow-sm rounded-2xl p-4 md:p-5 flex flex-col md:grid md:grid-cols-4 gap-4 items-end mt-2`">`n                                <div><label class=`"block text-xs font-bold mb-2 text-slate-600`">ละติจูด (Lat)</label><input type=`"text`" id=`"new-event-lat`" class=`"w-full px-5 py-3.5 rounded-2xl border border-slate-200 bg-white/80 focus:border-primary outline-none transition-all`" placeholder=`"(ไม่บังคับ)`"></div>`n                                <div><label class=`"block text-xs font-bold mb-2 text-slate-600`">ลองจิจูด (Lng)</label><input type=`"text`" id=`"new-event-lng`" class=`"w-full px-5 py-3.5 rounded-2xl border border-slate-200 bg-white/80 focus:border-primary outline-none transition-all`" placeholder=`"(ไม่บังคับ)`"></div>`n                                <div class=`"md:col-span-2`"><button type=`"button`" onclick=`"window.getCurrentAdminLocation('new-event-lat', 'new-event-lng')`" class=`"w-full px-6 py-3.5 bg-blue-50 text-blue-600 font-bold rounded-2xl hover:bg-blue-100 transition-colors shadow-sm flex justify-center items-center gap-2`"><i class=`"ph-bold ph-map-pin text-lg`"></i> ดึงพิกัด GPS ปัจจุบัน</button></div>"
)

$content = $content.Replace(
    "                <div><label class=`"block text-sm font-bold mb-2`">สถานที่</label><input type=`"text`" id=`"edit-event-location`" required class=`"w-full px-5 py-3.5 rounded-2xl border bg-slate-50 focus:border-primary focus:ring-4 focus:ring-primary/10 transition-all outline-none`"></div>`n                <button type=`"submit`" class=`"w-full py-4 mt-4 rounded-2xl font-bold text-white btn-gradient flex items-center justify-center gap-2`">บันทึกการแก้ไข</button>",
    "                <div><label class=`"block text-sm font-bold mb-2`">สถานที่</label><input type=`"text`" id=`"edit-event-location`" required class=`"w-full px-5 py-3.5 rounded-2xl border bg-slate-50 focus:border-primary focus:ring-4 focus:ring-primary/10 transition-all outline-none`"></div>`n                <div class=`"grid grid-cols-2 gap-4`">`n                    <div><label class=`"block text-sm font-bold mb-2`">ละติจูด (Lat)</label><input type=`"text`" id=`"edit-event-lat`" class=`"w-full px-5 py-3.5 rounded-2xl border bg-slate-50 focus:border-primary outline-none`"></div>`n                    <div><label class=`"block text-sm font-bold mb-2`">ลองจิจูด (Lng)</label><input type=`"text`" id=`"edit-event-lng`" class=`"w-full px-5 py-3.5 rounded-2xl border bg-slate-50 focus:border-primary outline-none`"></div>`n                    <div class=`"col-span-2`"><button type=`"button`" onclick=`"window.getCurrentAdminLocation('edit-event-lat', 'edit-event-lng')`" class=`"w-full py-3 bg-blue-50 text-blue-600 font-bold rounded-2xl border border-blue-100 hover:bg-blue-100 transition-colors flex items-center justify-center gap-2`"><i class=`"ph-bold ph-map-pin text-lg`"></i> ดึงพิกัด GPS ปัจจุบัน</button></div>`n                </div>`n                <button type=`"submit`" class=`"w-full py-4 mt-4 rounded-2xl font-bold text-white btn-gradient flex items-center justify-center gap-2`">บันทึกการแก้ไข</button>"
)

$content = $content.Replace("``${ev.status || 'open'}|${openT}|${closeT}|${certState}``", "``${ev.status || 'open'}|${openT}|${closeT}|${certState}|${ev.lat||''}|${ev.lng||''}``")
$content = $content.Replace("``${ev.status || 'open'}|||${certState}``", "``${ev.status || 'open'}|||${certState}|${ev.lat||''}|${ev.lng||''}``")
$content = $content.Replace("``${ev.status || 'open'}|${ev.openTime || ''}|${ev.closeTime || ''}|${checked ? 'true' : 'false'}``", "``${ev.status || 'open'}|${ev.openTime || ''}|${ev.closeTime || ''}|${checked ? 'true' : 'false'}|${ev.lat||''}|${ev.lng||''}``")
$content = $content.Replace("``open|${openT}|${closeT}|false``", "``open|${openT}|${closeT}|false|${document.getElementById('new-event-lat').value}|${document.getElementById('new-event-lng').value}``")
$content = $content.Replace("'open|||false'", "``open|||false|${document.getElementById('new-event-lat').value}|${document.getElementById('new-event-lng').value}``")
$content = $content.Replace("``${nS}|${e.openTime||''}|${e.closeTime||''}|${certState}``", "``${nS}|${e.openTime||''}|${e.closeTime||''}|${certState}|${e.lat||''}|${e.lng||''}``")
$content = $content.Replace("``${event.status || 'open'}|${event.openTime || ''}|${event.closeTime || ''}|${certState}``", "``${event.status || 'open'}|${event.openTime || ''}|${event.closeTime || ''}|${certState}|${document.getElementById('edit-event-lat').value}|${document.getElementById('edit-event-lng').value}``")

Set-Content -Path "C:\Users\Jenn1817\.gemini\antigravity\scratch\digit_crru\index.html" -Value $content -Encoding UTF8
