$file = 'C:\Users\Jenn1817\Downloads\digit_crru_frontend\index.html'
$text = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)

# The corrupted lines have:
#             { id: 'admin-certificates', label: 'ใบประกาศ', tabLabel: 'ใบประกาศ', icon: 'ph-certificate', roles: ['superadmin', 'activity'] }, 
#         };

$b64Target = "ICAgICAgICAgICAgeyBpZDogJ2FkbWluLWNlcnRpZmljYXRlcycsIGxhYmVsOiAn4LmD4Lia4Lib4Lij4Liw4LiB4Liy4LioJywgdGFiTGFiZWw6ICfguYDguJrguJvguKPguLDguIHguLLguKAnLCBpY29uOiAncGgtY2VydGlmaWNhdGUnLCByb2xlczogWydzdXBlcmFkbWluJywgJ2FjdGl2aXR5J10gfSwgCiAgICAgICAgfTs="

$b64Replacement = "ICAgICAgICAgICAgeyBpZDogJ2FkbWluLWNlcnRpZmljYXRlcycsIGxhYmVsOiAn4LmD4Lia4Lib4Lij4Liw4LiB4Liy4LioJywgdGFiTGFiZWw6ICfguYDguJrguJvguKPguLDguIHguLLguKAnLCBpY29uOiAncGgtY2VydGlmaWNhdGUnLCByb2xlczogWydzdXBlcmFkbWluJywgJ2FjdGl2aXR5J10gfSwgCiAgICAgICAgICAgIHsgaWQ6ICdhZG1pbi1zcHNzJywgbGFiZWw6ICdTUFNTJywgdGFiTGFiZWw6ICdTUFNTJywgaWNvbjogJ3BoLWNoYXJ0LWJhcicsIHJvbGVzOiBbJ3N1cGVyYWRtaW4nLCAnYWN0aXZpdHknXSB9LCAKICAgICAgICAgICAgeyBpZDogJ2FkbWluLXNldHRpbmdzJywgbGFiZWw6ICfguJXguLHguYnguIfguITguYjguIInLCB0YWJMYWJlbDogJ+C4leC4seC5ieC4h+C4hOC5iOC4gicsIGljb246ICdwaC1nZWFyJywgcm9sZXM6IFsnc3VwZXJhZG1pbiddIH0gCiAgICAgICAgXTsKICAgICAgICAKICAgICAgICBjb25zdCBTVEFUVVNfTUFQID0geyAKICAgICAgICAgICAgMTogeyB0ZXh0OiAn4Lij4Lit4LiV4Lij4Lin4LiI4Liq4Lit4LiaJywgY29sb3I6ICdiZy1hbWJlci0xMDAgdGV4dC1hbWJlci03MDAnLCBpY29uOiAncGgtaG91cmdsYXNzLWhpZ2gnIH0sIAogICAgICAgICAgICAyOiB7IHRleHQ6ICfguIrguYjguLPguKPguLDguYDguIfguK3guYDguIfguLTguJnguYHguKXguYnguKInLCBjb2xvcjogJ2JnLWVtZXJhbGQtMTAwIHRleHQtZW1lcmFsZC03MDAnLCBpY29uOiAncGgtY2hlY2stY2lyY2xlJyB9LCAKICAgICAgICAgICAgMzogeyB0ZXh0OiAn4LiB4Liz4Lil4Lix4LiH4Lic4Lil4Li04LiVJywgY29sb3I6ICdiZy1wdXJwbGUtMTAwIHRleHQtcHVycGxlLTcwMCcsIGljb246ICdwaC1zY2lzc29ycycgfSwgCiAgICAgICAgICAgIDQ6IHsgdGV4dDogJ+C4nuC4o+C5ieC4reC4oeC4o+C4seC4micsIGNvbG9yOiAnYmctYmx1ZS0xMDAgdGV4dC1ibHVlLTcwMCcsIGljb246ICdwaC1wYWNrYWdlJyB9IAogICAgICAgIH07CiAgICAgICAgY29uc3QgUk9MRV9NQVAgPSB7ICdzdXBlcmFkbWluJzogJ+C4n+C4ueC5ieC4lOC4ueC5geC4peC4o+C4sOC4muC4muC4quC4ueC4h+C4quC4uOC4lCcsICdhY3Rpdml0eSc6ICfguJ/guLnguYnguIjguLHguJTguIHguLLguKPguIHguLTguIjguIHguKPguKPguJInLCAnc2hvcCc6ICfguJ/guLnguYnguIjguLHguJTguIHguLLguKPguKPguYnguLLguJnguITguYnguIInIH07"

$target = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($b64Target))
$replacement = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($b64Replacement))
$text = $text.Replace($target, $replacement)

[System.IO.File]::WriteAllText($file, $text, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Restored incorrectly deleted lines successfully!"
