$file = 'C:\Users\Jenn1817\Downloads\digit_crru_frontend\index.html'
$text = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)

$b64Target = "ICAgICAgICAgICAgICAgIGNvbnN0IGxhdFZhbCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCduZXctZXZlbnQtbGF0JykgPyBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnbmV3LWV2ZW50LWxhdCcpLnZhbHVlIDogJyc7CiAgICAgICAgICAgICAgICBjb25zdCBsbmdWYWwgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnbmV3LWV2ZW50LWxuZycpID8gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ25ldy1ldmVudC1sbmcnKS52YWx1ZSA6ICcnOwogICAgICAgICAgICAgICAgY29uc3QgZmluYWxTdGF0dXMgPSAob3BlblQgfHwgY2xvc2VUKSA/IGBvcGVufCR7b3BlblR9fCR7Y2xvc2VUfXxmYWxzZXwke2xhdFZhbH18JHtsbmdWYWx9YCA6IGBvcGVufHx8ZmFsc2V8JHtsYXRWYWx9fCR7bG5nVmFsfWA7"
$b64Replacement = "ICAgICAgICAgICAgICAgIGNvbnN0IGxhdFZhbCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCduZXctZXZlbnQtbGF0JykgPyBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnbmV3LWV2ZW50LWxhdCcpLnZhbHVlIDogJyc7CiAgICAgICAgICAgICAgICBjb25zdCBsbmdWYWwgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnbmV3LWV2ZW50LWxuZycpID8gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ25ldy1ldmVudC1sbmcnKS52YWx1ZSA6ICcnOwogICAgICAgICAgICAgICAgY29uc3QgcmFkVmFsID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ25ldy1ldmVudC1yYWRpdXMnKSA/IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCduZXctZXZlbnQtcmFkaXVzJykudmFsdWUgOiAnJzsKICAgICAgICAgICAgICAgIGNvbnN0IGZpbmFsU3RhdHVzID0gKG9wZW5UIHx8IGNsb3NlVCkgPyBgb3Blbnwke29wZW5UfXwke2Nsb3NlVH18ZmFsc2V8JHtsYXRWYWx9fCR7bG5nVmFsfXwke3JhZFZhbH1gIDogYG9wZW58fHxmYWxzZXwke2xhdFZhbH18JHtsbmdWYWx9fCR7cmFkVmFsfWA7"

$target = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($b64Target))
$replacement = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($b64Replacement))

$text = $text.Replace($target, $replacement)
[System.IO.File]::WriteAllText($file, $text, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Updated createNewEvent successfully!"
